#!/usr/bin/env python3
"""Visualise the isolated lattice geometry across sizes.

Top row: geometry as generated by ``mc2d.lattice`` (absorber blocks, source
cell hatched, chimney channel dotted).  Bottom row: the scalar flux the
standard MC solver produces on that geometry, so the streaming channels and
the chimney are visible in the physics rather than just the drawing.

Usage: python scripts/lattice_explore.py [--k 3 5 7 9] [--n 400000]
                                         [--pitch 1.0] [--no-chimney]
"""
import argparse
import pathlib
import sys
import time

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from mc2d import run_transport  # noqa: E402
from mc2d.lattice import build_lattice, draw_lattice  # noqa: E402


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--k", type=int, nargs="+", default=[3, 5, 7, 9],
                    help="interior lattice cells per side (odd)")
    ap.add_argument("--pitch", type=float, default=1.0)
    ap.add_argument("--cells-per-pitch", type=int, default=16)
    ap.add_argument("--n", type=float, default=4e5, help="particles per case")
    ap.add_argument("--no-chimney", action="store_true")
    ap.add_argument("--seed", type=int, default=1)
    args = ap.parse_args()

    ks = args.k
    fig, axes = plt.subplots(2, len(ks), figsize=(3.5 * len(ks), 7.4),
                             squeeze=False)

    for col, k in enumerate(ks):
        prob = build_lattice(k, pitch=args.pitch,
                             chimney=not args.no_chimney,
                             cells_per_pitch=args.cells_per_pitch)
        spec = prob["spec"]

        draw_lattice(axes[0][col], spec)

        t0 = time.time()
        phi = run_transport(prob, int(args.n), seed=args.seed)
        dt = time.time() - t0
        print(f"K={k:2d}  L={spec['L']:5.1f} cm  mesh {prob['nx']}^2  "
              f"blocks={len(spec['absorber_boxes']):3d}  "
              f"{int(args.n):.0e} particles in {dt:5.1f} s  "
              f"max log10 phi = {np.log10(phi.max()):+.2f}")

        im = axes[1][col].imshow(np.log10(np.maximum(phi, 1e-30)),
                                 origin="lower", cmap="plasma",
                                 extent=[0, spec["L"], 0, spec["L"]],
                                 vmin=-6, vmax=0)
        axes[1][col].set_aspect("equal")
        axes[1][col].set_title(rf"$\log_{{10}}\phi$, N={int(args.n):.0e}",
                               fontsize=9)
        fig.colorbar(im, ax=axes[1][col], fraction=0.046)

    fig.suptitle("Lattice geometry and scalar flux vs lattice size K")
    fig.tight_layout()
    out = ROOT / "figures" / "lattice_sizes.png"
    fig.savefig(out, dpi=150)
    print("wrote", out)


if __name__ == "__main__":
    main()
